"""remove backdrop_url

Revision ID: 13b1c9cdb618
Revises: ec9d682a8c2a
Create Date: 2026-01-03 15:17:43.572377

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13b1c9cdb618"
down_revision: str | Sequence[str] | None = "ec9d682a8c2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "backdrop_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies",
        sa.Column(
            "backdrop_url", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
