"""Add movie url

Revision ID: 2235560df98d
Revises: eefd26f41b80
Create Date: 2026-01-23 17:52:39.516863

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2235560df98d"
down_revision: str | Sequence[str] | None = "eefd26f41b80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "showtimes", sa.Column("movie_url", sa.String(length=2048), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("showtimes", "movie_url")
    # ### end Alembic commands ###
