"""reinstate verbose location

Revision ID: 4b20989d22ed
Revises: 7a35c8fc73f3
Create Date: 2026-01-25 14:59:35.477094

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b20989d22ed"
down_revision: str | Sequence[str] | None = "7a35c8fc73f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cinemas", sa.Column("verbose_location", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cinemas", "verbose_location")
    # ### end Alembic commands ###
