"""rename-to-address

Revision ID: 7a35c8fc73f3
Revises: 993c270847f5
Create Date: 2026-01-25 14:53:44.301352

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a35c8fc73f3"
down_revision: str | Sequence[str] | None = "993c270847f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cinemas", sa.Column("address", sa.Text(), nullable=True))
    op.drop_column("cinemas", "verbose_location")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cinemas",
        sa.Column("verbose_location", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("cinemas", "address")
    # ### end Alembic commands ###
