"""add verbose location

Revision ID: 993c270847f5
Revises: 9980be720964
Create Date: 2026-01-25 11:19:51.679530

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "993c270847f5"
down_revision: str | Sequence[str] | None = "9980be720964"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cinemas", sa.Column("verbose_location", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cinemas", "verbose_location")
    # ### end Alembic commands ###
