"""Add IMDB ID

Revision ID: 9980be720964
Revises: 2235560df98d
Create Date: 2026-01-24 18:27:19.966075

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9980be720964"
down_revision: str | Sequence[str] | None = "2235560df98d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("imdb_id", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "imdb_id")
    # ### end Alembic commands ###
