"""add backdrop_url

Revision ID: ec9d682a8c2a
Revises: 8fa1687b9831
Create Date: 2025-12-30 10:01:44.971108

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec9d682a8c2a"
down_revision: str | Sequence[str] | None = "8fa1687b9831"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies", sa.Column("backdrop_url", sa.String(length=2048), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "backdrop_url")
    # ### end Alembic commands ###
